### ISSUE TITLE
Efter beställning ska det ej gå att ändra sin beställning 

### ISSUE THREAD

**Issue by jeppeerixon** [Medieinstitutet/fed22d-js-grundkurs-gruppuppgift-webbshop-treenigheten#11]
(lås input eller ta bort formulär) #11

**Comment by jeppeerixon** [comment]
Detta är kanske löst efter att vi döljer shop/beställning när man klickar vidare?

**Comment by evelinanorlin** [comment]
Jag har gjort en popup som låser allt annat. Kan jesper ta bort visability:hidden på munkarna? jag hittar inte den koden
