### ISSUE TITLE
Lista funktioner

### ISSUE THREAD

**Issue by evelinanorlin** [Medieinstitutet/fed22d-js-grundkurs-gruppuppgift-webbshop-treenigheten#6]
lista på funktioner som ska finnas i programmet

**Comment by jeppeerixon** [comment]
- Öka minsta antalet av en specifik munk
- Två bilder per munk
- Munk rating/betyg

- Efter Beställning visas bekräftelse med info + leveranstid
- Efter beställning ska det ej gå att ändra sin beställning (lås input eller ta bort formulär)

- Sortera munkar efter pris
- Sortera munkar efter kategori
- Sortera munkar efter namn
- Sortera munkar efter rating
- Filtrera munkar efter prisintervall

- Totalsumman updateras i realtid
- Visuell bekräftelse på uppdatering
- Varukorgsammanfattning
- Knapp för att tömma hela varukorgen
- Rabattkodsfält i varukorgen

- 10% rabatt innan kl 10 på måndagar (visuell info)
- Fredag 15:00 - Måndag 03:00 alla munkar 15% dyrare (hemligt)
- Mer än 800 kr ej möjligt att betala med faktura
- Om 10 munkar av samma sort = 10% rabatt på den munken
- Mer än 15 munkar = gratis frakt
- Frakt kostar 25kr + 10% av totalpriset
- Om kundar tar mer än 15 min på att beställa Alert: För långsam allt tas bort
- Om jämn vecka + tisdag = 25% rabatt om totalsumman över 25 kr
- Om luciadagen = gratis luciamunk
- Om juldagen = allt text röd + jultemabakgrund
- Om rabattkoden a_damn_fine-cup_of-coffee matas in, blir hela beställningen 0 kr oavsett övriga gällande specialregler.

- Standard Leveranstid 30 minuter
- Om det är helg 1,5h leveranstid
- Om det är mitt i natten 45 min leveranstid
- Om leveranstid fredag kl 11-13 leverans kl 15:00.

- Alla requiered formulärfält ska verifieras
- Alla formlärfält godkända = det går att beställa/klicka på knappen
- Om faktura valt ska personnr skrivas in
- Fel i formulär ska visas tydligt (a11y)
- Knapp för att rensa alla formulär

- Mörkttema (vg krav)

**Comment by jeppeerixon** [comment]
Färdigt enligt mig. Issues markerat med "good first issue" kan göras med HTML eller iallafall behövs fixas till en början med HTML/CSS.
